preload = /home/hoshikojima/Pictures/Wallpapers/wallpaper_left_aincrad.png
preload = /home/hoshikojima/Pictures/Wallpapers/wallpaper_right_crystal.png
wallpaper = HDMI-A-1,/home/hoshikojima/Pictures/Wallpapers/wallpaper_left_aincrad.png
wallpaper = DP-1,/home/hoshikojima/Pictures/Wallpapers/wallpaper_right_crystal.png
splash = false
