preload = /home/hoshikojima/.cursor/projects/home-hoshikojima-Documents-Projects-Yuna-by-Hoshi-hoshi-core/assets/wallpaper_left_aincrad.png
preload = /home/hoshikojima/.cursor/projects/home-hoshikojima-Documents-Projects-Yuna-by-Hoshi-hoshi-core/assets/wallpaper_right_crystal.png
wallpaper = HDMI-A-1,/home/hoshikojima/.cursor/projects/home-hoshikojima-Documents-Projects-Yuna-by-Hoshi-hoshi-core/assets/wallpaper_left_aincrad.png
wallpaper = DP-1,/home/hoshikojima/.cursor/projects/home-hoshikojima-Documents-Projects-Yuna-by-Hoshi-hoshi-core/assets/wallpaper_right_crystal.png
splash = false
